<?php
require __DIR__ . "/../vendor/autoload.php";
use Dompdf\Dompdf;
use Dompdf\Options;

include $_SERVER['DOCUMENT_ROOT'] . '../Database/connection.php';

header('Content-Type: application/json');
date_default_timezone_set('Asia/Manila');


$sql = "SELECT 
    s.ID as StockID, 
    IFNULL(s.Barcode, '') AS Barcode,
    i.ItemName, 
    i.ItemDesc, 
    i.Category, 
    i.Brand, 
    i.Model, 
    i.ReorderLevel, 
    s.QTY, 
    s.PriceCurrent, 
    CASE 
        WHEN s.ExpiryDate IS NULL THEN 'No Expiry' 
        ELSE s.ExpiryDate 
    END AS ExpiryDate
FROM items i
INNER JOIN stocks s ON s.ItemID = i.ID
        ORDER BY `ItemName` ASC, QTY ASC";

$result = $conn->query($sql);

$Items = [];
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $Items[] = $row;
    }
}

$conn->close();

// *********************************
//  HTML STRUCTURE STARTS HERE
// *********************************

$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="css/reports.css">
</head>
<body>
    <h1>List of Items as of {{ DateToday }} </h1>
    
    <table class="table-default">
        <thead>
            <tr>
                <th>Stock ID</th>
                <th>Barcode</th>
                <th>Item Name</th>
                <th>Item Description</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Reorder Level</th>
                <th>Current Stock</th>
                <th>Current Price</th>
                <th>Expiry Date</th>
            </tr>
        </thead>
        <tbody id="tableBody">';

foreach ($Items as $Item) {
    $html .= '
                <tr>
                    <td>' . htmlspecialchars($Item['StockID']) . '</td>
                    <td>' . htmlspecialchars($Item['Barcode']) . '</td>
                    <td>' . htmlspecialchars($Item['ItemName']) . '</td>
                    <td>' . htmlspecialchars($Item['ItemDesc']) . '</td>
                    <td>' . htmlspecialchars($Item['Category']) . '</td>
                    <td>' . htmlspecialchars($Item['Brand']) . '</td>
                    <td>' . htmlspecialchars($Item['Model']) . '</td>
                    <td>' . htmlspecialchars($Item['ReorderLevel']) . '</td>
                    <td>' . htmlspecialchars($Item['QTY']) . '</td>
                    <td>' . htmlspecialchars($Item['PriceCurrent']) . '</td>
                    <td>' . htmlspecialchars($Item['ExpiryDate']) . '</td>
                </tr>';

}
$html .= "
            <tr><td colspan='11' textalign = center>- - - NOTHING'S FOLLOW - - -</td></tr> 
        </tbody>
    </table>
    
</body>
</html>";

$html = str_replace("{{ DateToday }}", date('F j, Y'), $html);

// *********************************
//  HTML STRUCTURE ENDS HERE
// *********************************

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isPhpEnabled', true);
$options->set('chroot', __DIR__);

$dompdf = new Dompdf($options);
$dompdf->setPaper('Letter', 'landscape');
$dompdf->loadHtml($html);

$dompdf->render();

$canvas = $dompdf->getCanvas();
$canvasWidth = $canvas->get_width();
$canvasHeight = $canvas->get_height();

session_start();
$LoggedinUser = $_SESSION['LoggedinUser'] ?? 'Unknown User';
$canvas->page_text(50, $canvasHeight - 75, 'Generated by: ' . $LoggedinUser, null, 8, array(0, 0, 0));

$currentDateTime = date('l, F j, Y h:i A');
$canvas->page_text(50, $canvasHeight - 60, 'Generated on: ' . $currentDateTime, null, 8, array(0, 0, 0));

$footerText = "Page {PAGE_NUM} of {PAGE_COUNT}";
$canvas->page_text($canvasWidth - 100, $canvasHeight - 75, $footerText, null, 10, array(0, 0, 0));


$dompdf->stream("List_Of_Items" . $currentDateTime . ".pdf", ["Attachment" => 0]);
?>