<?php
require __DIR__ . "/../vendor/autoload.php";
use Dompdf\Dompdf;
use Dompdf\Options;

include $_SERVER['DOCUMENT_ROOT'] . '../Database/connection.php';

header('Content-Type: application/json');
date_default_timezone_set('Asia/Manila');


$sql = "SELECT 
            t1.DateTimeCreated AS TransactionDate,
            t1.ActionTaken,
            t1.QTY,
            t3.ItemName,
            t3.ItemDesc,
            t3.Category,
            t3.Brand,
            t3.Model,
            t2.ExpiryDate
        FROM
            invtransaction t1
            INNER JOIN stocks t2 ON t1.StockID = t2.ID
            INNER JOIN items t3 ON t2.ItemID = t3.ID
        ORDER BY `TransactionDate` DESC";

$result = $conn->query($sql);

$suppliers = [];
if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $suppliers[] = $row;
    }
}

$conn->close();

// *********************************
//  HTML STRUCTURE STARTS HERE
// *********************************

$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="css/reports.css">
</head>
<body>
    <h1>List of Categories as of {{ DateToday }} </h1>
    
    <table class="table-default">
        <thead>
            <tr>
                <th>Transaction Date</th>
                <th>Action Taken</th>
                <th>Quantity</th>
                <th>Item Name</th>
                <th>Item Description</th>
                <th>Category</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Expiry Date</th>
            </tr>
        </thead>
        <tbody id="tableBody">';

foreach ($suppliers as $supplier) {
    $html .= '
                <tr>
                    <td>' . htmlspecialchars($supplier['TransactionDate']) . '</td>
                    <td>' . htmlspecialchars($supplier['ActionTaken']) . '</td>
                    <td>' . htmlspecialchars($supplier['QTY']) . '</td>
                    <td>' . htmlspecialchars($supplier['ItemName']) . '</td>
                    <td>' . htmlspecialchars($supplier['ItemDesc']) . '</td>
                    <td>' . htmlspecialchars($supplier['Category']) . '</td>
                    <td>' . htmlspecialchars($supplier['Brand']) . '</td>
                    <td>' . htmlspecialchars($supplier['Model']) . '</td>
                    <td>' . htmlspecialchars($supplier['ExpiryDate']) . '</td>
                </tr>';

}
$html .= "
            <tr><td colspan='9' textalign = center>- - - NOTHING'S FOLLOW - - -</td></tr> 
        </tbody>
    </table>
    
</body>
</html>";

$html = str_replace("{{ DateToday }}", date('F j, Y'), $html);

// *********************************
//  HTML STRUCTURE ENDS HERE
// *********************************

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isPhpEnabled', true);
$options->set('chroot', __DIR__);

$dompdf = new Dompdf($options);
$dompdf->setPaper('Letter', 'landscape');
$dompdf->loadHtml($html);

$dompdf->render();

$canvas = $dompdf->getCanvas();
$canvasWidth = $canvas->get_width();
$canvasHeight = $canvas->get_height();

session_start();
$LoggedinUser = $_SESSION['LoggedinUser'] ?? 'Unknown User';
$canvas->page_text(50, $canvasHeight - 75, 'Generated by: ' . $LoggedinUser, null, 8, array(0, 0, 0));

$currentDateTime = date('l, F j, Y h:i A');
$canvas->page_text(50, $canvasHeight - 60, 'Generated on: ' . $currentDateTime, null, 8, array(0, 0, 0));

$footerText = "Page {PAGE_NUM} of {PAGE_COUNT}";
$canvas->page_text($canvasWidth - 100, $canvasHeight - 75, $footerText, null, 10, array(0, 0, 0));


$dompdf->stream("List_Of_Items" . $currentDateTime . ".pdf", ["Attachment" => 0]);
?>